sudo: false

matrix:
  include:
    - language: python
      python: 3.7
      cache: pip
      install:
        - pip install jupyter nbconvert
      before_script:
        - python build/build_pages.py

    - language: node_js
      node_js: 10
      cache: npm
      branches:
        only:
          - master
      script:
        - hexo generate
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        on:
          branch: master
        local-dir: public

notifications:
  email:
    - tim.hargreaves@icloud.com